// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpz0_BPNbLWZbXmQUbmFKkUsJRGSJg2Ss',
    appId: '1:65146427281:web:cb78e1d7bbfcf90b6bec30',
    messagingSenderId: '65146427281',
    projectId: 'eczema-self-assessment',
    authDomain: 'eczema-self-assessment.firebaseapp.com',
    storageBucket: 'eczema-self-assessment.firebasestorage.app',
    measurementId: 'G-Y1QM49BDJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgRb1trZMgERs4o3-EHqCeNZZPqKcTazg',
    appId: '1:65146427281:android:5ff2167877ca52d36bec30',
    messagingSenderId: '65146427281',
    projectId: 'eczema-self-assessment',
    storageBucket: 'eczema-self-assessment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYGfxVKRhs_ILUubvJKlyN-he3W-xYj_c',
    appId: '1:65146427281:ios:debd144e6dff98136bec30',
    messagingSenderId: '65146427281',
    projectId: 'eczema-self-assessment',
    storageBucket: 'eczema-self-assessment.firebasestorage.app',
    iosBundleId: 'com.charlie.eczemaSelfAssessment2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYGfxVKRhs_ILUubvJKlyN-he3W-xYj_c',
    appId: '1:65146427281:ios:f684ae30144b4b466bec30',
    messagingSenderId: '65146427281',
    projectId: 'eczema-self-assessment',
    storageBucket: 'eczema-self-assessment.firebasestorage.app',
    iosBundleId: 'com.example.eczemaSelfAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpz0_BPNbLWZbXmQUbmFKkUsJRGSJg2Ss',
    appId: '1:65146427281:web:b99218053e1cb8cc6bec30',
    messagingSenderId: '65146427281',
    projectId: 'eczema-self-assessment',
    authDomain: 'eczema-self-assessment.firebaseapp.com',
    storageBucket: 'eczema-self-assessment.firebasestorage.app',
    measurementId: 'G-XQRN3HD8WX',
  );
}
